### ISSUE TITLE
Change ZipCode Input Box for Demographics.csv

### ISSUE THREAD

**Issue by TutiGomoka** [Watts-Lab/surveyor#112]
Since we are allowing people from many countries in the world to fill out our surveys, can we adjust the zip code box of the demographics survey to be a format that takes American zip code numbers as well as other country's postal code systems?

**Comment by TutiGomoka** [comment]
But wouldn't text response limit to just characters?

**Comment by markwhiting** [comment]
No.

**Comment by TutiGomoka** [comment]
OK; Let me try that;

**Comment by TutiGomoka** [comment]
Just tested with a link I created for myself; It works with letters now. Will email the worker who emailed with a new link. 
<img width="1440" alt="Screen Shot 2022-08-09 at 11 32 15 AM" src="https://user-images.githubusercontent.com/35717402/183694298-b301a74c-f624-468c-b204-5274e987ba0a.png">
<img width="1440" alt="Screen Shot 2022-08-09 at 11 32 03 AM" src="https://user-images.githubusercontent.com/35717402/183694300-84284d56-e3cb-407c-ae9a-a238d982c4f3.png">

Closing this now @markwhiting

**Comment by TutiGomoka** [comment]
Adding another random link with workers 'mark' incase we ever want to test again https://surveyor.seas.upenn.edu/sa/mwxuaqVV9wvEIQ

**Comment by markwhiting** [comment]
Great!
