### ISSUE TITLE
🦾 Turk infrastructure overhall

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/surveyor#119]
We are revisiting the turk infrastructure to be more familiar to workers, more capable of dealing with multiple turk accounts for accounting purposes, and more easy to maintain. A more detailed proposal is here https://github.com/Watts-Lab/surveyor/issues/114 but it's also not final, as we are still testing some aspects and scheduled to speak with CloudResearch to see if their tools can mitigate some of our planned development work.

**Comment by duncanjwatts** [comment]
What happened with AMT threatening to block our account? Why do they not like us running our own surveys?

**Comment by markwhiting** [comment]
They don't like people managing workers off-platform, which we were doing with our notification system.

**Comment by JamesPHoughton** [comment]
Yeah, I've had this flagged before just for sending email notifications for normal HITs that point to empirica. Its really opaque to me what it is they care about...

How does turk know what we're doing, other than through worker complaints?

**Comment by markwhiting** [comment]
As far as I know it's only via complaints, but I guess it could be that they see that you are sending too many notifications and bonuses, and not enough HITs?
