### ISSUE TITLE
Insight from talking with Cloud Research

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/surveyor#120]
Cloud research provides a possible alternative to our internal panel tool. We met with them to see if it could save us some development time or help us navigate any issues that have been getting in our way. 

After meeting with them, I think they provide some interesting tools but have largely not solved any of the harder aspects of what we are doing. For example, they don't have a great solution for simultaneous experiments or for ongoing panel development.

My current proposal is that we do not go this rout and instead try to start by manual approaches to the new architecture, and slowly implement it more completely for use by the group → https://github.com/Watts-Lab/surveyor/issues/114

**Comment by JamesPHoughton** [comment]
I agree that they don't seem to add significantly more value for us. They could be useful for one-off situations that want a large number of participants broken down into groups of 9 or smaller to avoid the MTurk 40% overhead rate.

They have a panel of their own that aims to do what prolific and mturk do, it is small at the moment, and they charge a 25% overhead, and doesn't seem to add much at the moment.

Would still be worth checking in with them in 2 years to see where they are
