### ISSUE TITLE
Configure for production

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/surveyor#13]
We need: 
- [x] A server with push based deployment, probably EC2.
- [x] Github actions for any relevant deployment, CI, CD etc.
- [x] A static IP from AWS.

@yli12313 can you help us think about how to get these things set up for this. Would be great to be launched by sometime next week. 

A few questions we might need to answer are: 
1. What do we need to change to be ready for production?
2. Should be remove `nedb` or can we keep it as a dev configuration and use Dynamo as a production configuration?

**Comment by yli12313** [comment]
@markwhiting : the server, static IP and database, definitely yes and I can set it up if you give me an idea of the specs. The GitHub Actions I'm new too...I know it's a YAML configuration. Mark, do you want to talk about this sometime Monday?

**Comment by markwhiting** [comment]
I think we can start with something reasonably light weight. Probably we want to be able to handle about 500 simultaneous requests at max, and I think most configurations should be fine with that.

For DB I don't know how the specs work exactly but I assume we need less than 1GB for now but will get larger than that over time. I think Dynamo scales with size though so that shouldn't be a problem. 

Yes, GH Actions are YAML (I wish they were something else) and I think there should be some existing examples for things like compiling Type script and running standard checks. I'm not sure we need to do it that way but it should be free for us, so it might be interesting to try.

**Comment by yli12313** [comment]
Ok... good to know. I think I could even do this in real-time during our meeting Monday. Getting an EC2 and RDS provisioned should take really minutes! Let me look for into GitLab Actions and see if there are templates available. Best, Y

**Comment by markwhiting** [comment]
Thanks. I agree that it should be fast, just want to make sure we don't mess anything up in the configuration.

Here's where I would look → https://docs.github.com/en/actions

**Comment by markwhiting** [comment]
Short notes from our meeting: 

1. probably we don't need the DB stuff yet, lets focus on the server for now. 
2. main concerns for now are pushing changes from GitHub to EC2 and having the server relaunch. 
3. [PM2](https://www.npmjs.com/package/pm2) might be a good way to do this.

**Comment by markwhiting** [comment]
@yli12313 another option here would be to host this as a lambda function or to otherwise make this server less. I don't have enough insight to understand the full implications that might have on other aspects of the system, and I don't know how it would impact costs, but it might mean that some aspects are more straightforward. 

Do you have any thoughts on that?

**Comment by yli12313** [comment]
@markwhiting : I would have to do some exploration myself with regard to Lambda functions. I know its cost-effective, but it's sometimes unintuitive to get things working with it. Let me get back to you with what I find.

**Comment by markwhiting** [comment]
OK!

**Comment by yli12313** [comment]
Mark to give you an update:

- I got the code onto a server. I created an endpoint and used PM2 that will always start the application whenever the server starts/re-starts. 
- I hosted the app so that it's publicly accessible. 
- I got the git to push any code changes directly from a local server to the remote server. I believe PM2 will update such changes in real-time when you make a change.

I just haven't had the time I thought this week to really look at this deeply. I will continue trying... if you believe I should pivot, please do let me know! - Best, Y

**Comment by yli12313** [comment]
Yingquan got deployments working with GitHub actions on his branch: **test_yl**.

**Comment by yli12313** [comment]
I believe the PR needs approval... I think the only thing that could potentially need changing is the fact that the workflow right now is customized to my test branch **test_yl**. It probably needs to be changed to say **main** if being deployed to production... but we can take it slow and just keep it the way it is, and then just change the branch when needed. Going to look @ serverless and try some simple prototypes.

**Comment by markwhiting** [comment]
Great, approved. I'll mark this as closed for now and we can open something around the server less stuff if that look promising.
