### ISSUE TITLE
Adding factor loadings and reverse coding into IRQ

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/surveyor#16]
Factor loadings are here → https://link.springer.com/article/10.3758/s13428-020-01354-y/tables/2 

I think I would just do this as columns with a name like `IRQ_visual` etc. 

Reverse coding is shown with a star in the question text. I think we currently have those stars in the presented text, and they should be removed from there and those questions should be set as reverse. Perhaps its worth double checking that the table above and our version match in coding and otherwise.

**Comment by KaranSampath** [comment]
Updated IRQ in #18 . Do we want to update `survey.pug` to read this or does surveyor not care about this?

**Comment by markwhiting** [comment]
Lets not do anything within surveyor for this for now. There's a few things we could do later if we decide to.

**Comment by KaranSampath** [comment]
Alright. I think this issue can be closed for now.
