### ISSUE TITLE
Add a CSV specification with an example to the README

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/surveyor#50]
Address, what each column does and which ones are optional. Also provide an example and perhaps link to the survey folder. See the [individual mapping README](https://github.com/Watts-Lab/individual-mapping#donating-a-new-dataset) as a possible example.

**Comment by markwhiting** [comment]
Should this be closed?

**Comment by markwhiting** [comment]
@sumants-dev — just checking, was this closed by mistake?

**Comment by sumants-dev** [comment]
Yes
