### ISSUE TITLE
Add in check for required columns in CSVs

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/surveyor#53]
Now, if theres a row in the CSV with missing columns out of the required ones we get some strange behavior. For example it makes other things later in the survey an open multi select item because of the way the conditions are set in `survey.pug`. I think we should fix this so that lines in the CSV are skipped if theres an issue with them.

**Comment by KaranSampath** [comment]
Just wanted to clarify, do you mean a missing column for the entire CSV here, or if something is wrong with an individual entry for a required column? Have added checks for the former, but not for the latter (would need more clarity on what all checks we want then)

**Comment by markwhiting** [comment]
I think the former is ok for now.
