### ISSUE TITLE
Create More Robust Submission Message That Are Pipeable

### ISSUE THREAD

**Issue by sumants-dev** [Watts-Lab/surveyor#63]

**Comment by markwhiting** [comment]
Related to a comment in #60

**Comment by KaranSampath** [comment]
Could be a url argument (for it to be really customizable) but will need to be explored. Could have a set of defaults as well

**Comment by sumants-dev** [comment]
Yeah, it should have set default of "Thank you for completing our Survey!", I think for now you can safely assume the pipeable end of surveys should be just plain text.

For anything else more complicated, we will incorporate it into link generation service.

**Comment by karansampath** [comment]
Closing for now (not needed)
