### ISSUE TITLE
Multi page surveys

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/surveyor#8]
Set up to manage multiple pages, e.g., RME, using something like a page column.

**Comment by markwhiting** [comment]
- [ ] How do we tell the system about pages? Whats on a new page, whats the order, can you go back?
- [ ] Do you store incrementally at each page? if so, how? (i.e., one row in DB per page, or a local object thats dumped in DB when no more pages come in)
- [ ] Does the back end give all pages at once, or one page at a time?

**Comment by markwhiting** [comment]
See here for more → https://github.com/Watts-Lab/surveyor/issues/1#issuecomment-895261068

**Comment by markwhiting** [comment]
@KaranSampath can you try to solve this next?

**Comment by markwhiting** [comment]
How's this going?

**Comment by KaranSampath** [comment]
Was focused on task mapping for the past week so haven't done much on this yet. I should have a good idea of how to go about this by tomorrow's meeting.

**Comment by markwhiting** [comment]
OK. Thats fine, task mapping is more time critical for now.

**Comment by KaranSampath** [comment]
- [ ] User disconnects/closes, we should only save the final survey
- [ ] Add disclaimer saying that 'You cannot come back to this page' at the end of every page
- [ ] Add `.page` column to allow for alphanumeric ordering of pages
- [ ] Allow for randomization of letters/numbers in `.page`
- [ ] Modify RME survey to be multi-page and check which of the other surveys are designed to be single page only

**Comment by markwhiting** [comment]
Check in. When do you think this can be completed?

**Comment by KaranSampath** [comment]
Sorry, was under the weather with COVID-like symptoms. Surveys have been modified, and am working on modifying VSCode now. Will ensure it is done by tomorrow.

**Comment by KaranSampath** [comment]
Having been working on this in #40

**Comment by markwhiting** [comment]
Just checking in, is this basically done?

**Comment by sumants-dev** [comment]
@KaranSampath if you need help and blocked, we can set up a time to go through it next week
