### ISSUE TITLE
Mid-Survey Challenge Question

### ISSUE THREAD

**Issue by TutiGomoka** [Watts-Lab/surveyor#89]
Enable our ability to add a challenge question mid-survey

**Comment by markwhiting** [comment]
Do we need this? Is there something wrong with where they are now?

**Comment by TutiGomoka** [comment]
Just in the future. As in the current structuring we have now is v1. We said we would try doing this in the future. So this is an *in the future* issue that I created with @sumants-dev

**Comment by markwhiting** [comment]
Marking complete because I think we have a solid solution for now, and other changes to rendering (e.g., #85) will eventually change our options here.
