### ISSUE TITLE
Timestamps per question/stage of survey

### ISSUE THREAD

**Issue by TutiGomoka** [Watts-Lab/surveyor#98]
Right now we have `start_time` and `end_time`. Perhaps in the future it would be good @sumants-dev to have timestamps on when people finished certain middle questions. Ideally, instead of this being multiple variables, we can have one variable that is a list with different durations of each question` i.e. {25seconds, 30seconds... }} or {11:48, 11:49, .....}`

**Comment by markwhiting** [comment]
Just noting that I'm not really sure what the best model is for this, e.g., a list of times, or a column of times for each response, or something else, and happy to think about that a bit as part of this issue.
